/**
 * De opslaglaag. Sinds 05-10 wonen de functies per domein in api/_lib/opslag/;
 * dit bestand geeft ze alleen door, zodat elke bestaande import (en elke
 * vi.mock van storage.js) blijft werken. Nieuwe opslagfuncties horen in het
 * domeinbestand en krijgen hier een regel bij.
 */
export {
  isMissingDbFunction,
  type PaginaTelling,
  paginatedFetch,
} from "./_lib/opslag/basis.js";
export {
  type PlanningFilters,
  getPlanningData,
  getPlanningHorizon,
  savePlanningData,
  getShiftById,
  getShiftsOnDate,
  saveMatrixRowAssignments,
  insertPlanningRows,
  clearPlanningData,
  replacePlanningData,
  getPlanningVersion,
  getPlanningMatrixRows,
  replacePlanningAndMatrix,
  getPlanningCodesData,
  savePlanningCodesData,
  getPlanningMatrixHistory,
  savePlanningMatrixHistoryEntry,
  type ImportSnapshot,
  storeImportSnapshot,
  getImportSnapshot,
  restorePlanningAndMatrixSnapshot,
  getLatestBackup,
  type PlanningNoteRow,
  getPlanningNotes,
  upsertPlanningNote,
  deletePlanningNote,
  type UserExpiryRecord,
  getUserExpiries,
  saveUserExpiry,
  deleteUserExpiry,
} from "./_lib/opslag/planning.js";
export {
  getActivityLog,
  getLoginActivity,
  getRecentLogins,
  getLatestAuthEventAt,
  getSwapHistories,
  type SwapVerloopLogRegel,
  getSwapVerloopRegels,
  getSwapExecutions,
  getEntityHistory,
  logActivity,
  type AanwezigheidSessie,
  vergeetPresenceLocatie,
  noteerAanwezigheid,
  getAanwezigheid,
} from "./_lib/opslag/activiteit.js";
export {
  summarizeTokens,
  summarizeUserChanges,
  summarizePlanningCodeChanges,
  diffServiceChanges,
  summarizeServiceChanges,
  diffDiversionChanges,
  diffUpdateChanges,
  diffUserChanges,
  diffPlanningCodeChanges,
  summarizeDiversionChanges,
  summarizeUpdateChanges,
} from "./_lib/opslag/wijzigingen.js";
export {
  isValidHHMM,
  getServiceSegments,
  buildPlanningFromMatrix,
  bouwPlanningUitMatrix,
} from "./_lib/opslag/planningOpbouw.js";
export {
  EmailInGebruikError,
  OOK_TECHNIEKER_MIGRATIE,
  MigratieOntbreektError,
  getUsersData,
  type NieuwAccount,
  saveUsersData,
  koppelAuthId,
  updateUserSessionMeta,
  updateUserDashboardVoorkeuren,
  bumpActiveSessions,
} from "./_lib/opslag/gebruikers.js";
export {
  DIVERSIONS_BUCKET,
  diversionBijlagePad,
  diversionLegacyPad,
  uploadDiversionBijlage,
  verwijderDiversionBijlage,
  verwijderDiversionLegacyBijlage,
  verplaatsDiversionLegacyBijlage,
  DIVERSION_URL_TTL_SEC,
  ondertekenDiversionBijlage,
  downloadDiversionBijlage,
  zetDiversionBijlagen,
  bestaandeDiversionBijlagen,
  type BijlageBestand,
  lijstBijlageBestandenVolledig,
  lijstBijlageBestanden,
  telRijen,
  verwijderBijlageBestanden,
  GERICHTE_LEZING_MAX,
  bestaandeRecordIds,
  logregelsVanEntiteiten,
  getDiversionsData,
  saveDiversionsData,
} from "./_lib/opslag/omleidingen.js";
export {
  getServicesData,
  saveServicesData,
  getCoverageExpectations,
  saveCoverageExpectations,
} from "./_lib/opslag/diensten.js";
export {
  storeBackup,
  type RestorableCollections,
  checkBackupIntegrity,
  restoreFromBackup,
} from "./_lib/opslag/backups.js";
export {
  DOCUMENTS_BUCKET,
  type UserDocumentRecord,
  listUserDocuments,
  getUserDocument,
  insertUserDocument,
  markUserDocumentOpened,
  deleteUserDocument,
  getRitblaadjeMeta,
  kopieerOnthaalDocumentenNaar,
  deleteAllDocumentsForUser,
} from "./_lib/opslag/documenten.js";
export {
  type ClientErrorEntry,
  logClientError,
  type ClientErrorStatusRecord,
  getClientErrorStatuses,
  setClientErrorStatus,
  getClientErrors,
  getClientErrorsSince,
  pruneOldRecords,
} from "./_lib/opslag/fouten.js";
export {
  bewaarMeldingen,
  getMeldingen,
  telOngelezenMeldingen,
  markeerMeldingenGelezen,
  verwijderMeldingen,
} from "./_lib/opslag/meldingen.js";
export {
  getUpdatesData,
  UPDATE_BIJLAGEN_BUCKET,
  updateBijlagePad,
  uploadUpdateBijlage,
  verwijderUpdateBijlage,
  UPDATE_BIJLAGE_URL_TTL_SEC,
  ondertekenUpdateBijlage,
  zetUpdateBijlagen,
  bestaandeUpdateBijlagen,
  saveUpdatesData,
  markUpdatesRead,
  getUpdateReadIdsForUser,
  getUpdateReadCounts,
} from "./_lib/opslag/updates.js";
export {
  getDevice,
  registerDevice,
  listDevicesForUser,
  listAllDevices,
  listRevokedSessionIds,
  setDeviceStatus,
  renameDevice,
  deleteDevice,
  revokeAllDevices,
} from "./_lib/opslag/toestellen.js";
export {
  getSwapsData,
  getPlanningMatrixGrenzen,
  getSwapsByIds,
  saveSwapsData,
  schrijfSwapAlsStatus,
  voegSwapsToe,
  markSwapTargetSeen,
  type SwapCarryFields,
  swapHasReturnShift,
  swapRaaktBereik,
  applySwapsToPlanningRows,
  type SwapCarryResult,
  type SwapBenen,
  applySwapToPlanning,
  revertSwapFromPlanning,
  swapToestandInPlanning,
} from "./_lib/opslag/ruilen.js";
export {
  getLeaveData,
  saveLeaveData,
} from "./_lib/opslag/verlof.js";
export {
  type MailLogRegel,
  logMail,
  startMailLog,
  rondMailLogAf,
  type MailLogRij,
  getMailLog,
  logCronHeartbeat,
  getCronHeartbeats,
  getAppSetting,
  setAppSetting,
} from "./_lib/opslag/systeem.js";
export type { DeviceStatus } from "./types.js";
export type { UserDevice } from "./types.js";
